### ISSUE TITLE
[Throughput Monitor] Average Bar not moving

### ISSUE THREAD

**Issue by ghost** [SebastienGllmt/Anki-Addons#6]
![2019-08-18_19-58-09](https://user-images.githubusercontent.com/13769570/63226434-f89a6a00-c1c8-11e9-979a-18a89afc7528.gif)
As indicated in the GIF, the average bar does not change values during review.

**Comment by SebastienGllmt** [comment]
Strange. It works fine for me on both Windows and Mac and other people have it working also but it also seems you're not the only one running into this since this was also mentioned in #4 (EDIT: oh I didn't notice this was also you)

Can you think of anything about your particular setup that would cause this?

The two most likely causes for this error:
1) The function `updateThroughputOnAnswer` (which updates the bar) should be called on the hook `Scheduler.answerCard`. Maybe this doesn't get called? Possibly a different addon is messing with this hook?
2)  You have a different addon that changes `card.type` (new, learning, matured, etc.) so this addon doesn't know how many points should be given for this review type.

**Comment by ghost** [comment]
I've tried it with all addons disabled so that's out of the way.
The only thing I can think of is that I'm using the V2 scheduler.

**Comment by SebastienGllmt** [comment]
Awesome, the scheduler v2 was the issue! I fixed it in 5f363f9 and issued a patch. Update your version of the addon to fix the issue 👍
